### ISSUE TITLE
Change did to be hash of public key

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#17]
### Description
Currently the DID is the first 16 characters of the base58 encoded public key. It should be changed to the sha3 hash of the public key instead, this makes integration with Ethereum easier and guarantees a fixed DID size without awkward string manipulation.

### TODO: 
- [x] Update the generation code.
- [x] Update the corresponding tests and test files.

**Comment by Exulansis** [comment]
I assume further changes need to be made in the appropriate branches @katszwn @charleenfei.

**Comment by katszwn** [comment]
@Exulansis integrated in https://github.com/jolocom/jolocom-lib/pull/11

**Comment by Exulansis** [comment]
@katszwn Thank you, closing.
