### ISSUE TITLE
Unable to create Identity Wallet

### ISSUE THREAD

**Issue by sandramarianegeorge** [jolocom/jolocom-lib#257]
```typescript
const IdentityWallet = await registry.authenticate(vaultedKeyProvider, {
  derivationPath: JolocomLib.KeyTypes.jolocomIdentityKey,
  decryptionPass: password
})
```

fails with the following error : 

`UnhandledPromiseRejectionWarning: TypeError: Key must be a buffer`

Can you suggest a fix for this ?

**Comment by Exulansis** [comment]
Thank you for reporting, updating the documentation. There was a slight typo, where `decryptionPass` should actually be `encryptionPass`. Updating the docs now, and let me know if this solves the issue.
