### ISSUE TITLE
Remove web3 dependency

### ISSUE THREAD

**Issue by palinka** [jolocom/jolocom-lib#280]
### Description
When adding our lib to a project, web3 in the version we use produces warnings which is not nice for our users:
```
warning jolocom-lib > jolocom-registry-contract > web3 > web3-bzz > swarm-js > fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
warning jolocom-lib > jolocom-registry-contract > web3 > web3-bzz > swarm-js > tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
```
 As far as I know we just use it in our tests, see #272.

Lets remove it completely?

Check 
- [ ] Above warnings are gone when adding our lib to a project.
- [ ] Integration tests use a newer version of web3 (without warnings) or do not use web3 anymore.

**Comment by palinka** [comment]
https://github.com/jolocom/jolocom-lib/pull/279/commits/f0268529108ab41b3e39238d79fab1d798a7f27f

**Comment by palinka** [comment]
If we do not remove web3, we should think to use a newer version.

**Comment by palinka** [comment]
This branch could be used: https://github.com/jolocom/jolocom-lib/pull/279

**Comment by chunningham** [comment]
web3 has since been removed as a direct dependancy, closing
