### ISSUE TITLE
JolocomLib.util.validateDigestable fails with '@context must be an object.'

### ISSUE THREAD

**Issue by palinka** [jolocom/jolocom-lib#285]
**Describe the bug**
Although following https://jolocom-lib.readthedocs.io/en/latest/, JolocomLib.util.validateDigestable fails with above error.

I had the _impression_ this did not happen before 19th of March, but can be reproduced 100% since then. Need to check eventual external dependencies for context..

Here more infos:

identityWallet.create.signedCredential returns an array for the context:

![Screenshot from 2019-03-22 10-32-02](https://user-images.githubusercontent.com/856957/54815181-a8f35900-4c91-11e9-9734-fb17236e30a6.png)

JolocomLib.parse.signedCredential return undefined as consequence for above:

![Screenshot from 2019-03-22 10-32-20](https://user-images.githubusercontent.com/856957/54815188-abee4980-4c91-11e9-9c80-1c845f9e32c6.png)

**To Reproduce**
I implemented a self-contained unit-test here.

Use `yarn testSignatureValidation` to execute. 

**Expected behavior**
A credential can be signed by JolocomLib.

** TODO **
* Downgrade json-ld for an A/B test
* It may be the case the DID spec is not complaint with the json-ld spec.

**Comment by palinka** [comment]
According to the DID spec, a DID document MUST have exactly one context: https://w3c-ccg.github.io/did-spec/#contexts

**Comment by palinka** [comment]
json-ld was updated here: https://github.com/jolocom/jolocom-lib/commit/025364e73b43e21827ec1a9ebe2c1ab0243af75f

Maybe this is connected and did not bubble up, because
- Neither unit- nor integration tests of the lib catch the bug.
- Backend do sign, but are not yet updated to jolocom-lib 2.3.0.
- The SmartWallet does not sign.

**Comment by chunningham** [comment]
The JSON-LD spec does not specify what type the @context block should be and the VC spec has an example with an array. The JSON-LD library is not processing the context field properly I suspect.

**Comment by Exulansis** [comment]
Does this still need to be addressed? Otherwise I can close this.

**Comment by Exulansis** [comment]
@chunningham @mnzaki @VolkerSchiewe
I am closing this issue for now, if this reoccurs in some way, this can be reopened.
