### ISSUE TITLE
Add a basic authentication procedure

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#3]
For authentication, we should use a mechanism of cryptographic signature with a private key and verification of the signature with a public key. We can use https://github.com/digitalbazaar/jsonld-signatures to create JSON-LD compatible signature.

**Comment by Exulansis** [comment]
Can we perhaps be more specific? Maybe include some information form the document outlining the process.

**Comment by nataschaberg** [comment]
The authentication process should proof authenticity of DID by means of comparing a signed message with the public key contained within the resolved DDO. The following steps are involved:

1. U sends DID on interaction to S 
2. S resolves DID to DDO containing public key
3. S sends some random string to U
4. U signs string and sends it back to S
5. S compares signed string with public key from DDO (outcome: either true or false)

U = User
S = Service

**Comment by nataschaberg** [comment]
Improvement of authentication process as below:
1.   Service site displays log in with JOLOCOM
2.   User scans QR code which contains information on:
     - DID of service
     - requested claims / verified claims 
     - random room IPFS
3.   App verifies DID of service 
4.   User accepts interaction and send back requested claims to IPFS random room 
5.   Service gets notified that information was added to room
6.   Service resolves verified claim hashes to information
      - checks the issuer of verification
      - service chooses if it wants to trust the verified information
7.   User is authenticated

Following steps need to be implemented:
- [ ] requesting infromation via QR code
- [ ] implementation of JWT for information exchange
- [ ] implementation of IPFS pub sub
- [ ] implementation of IPFS hash claim resolving
