### ISSUE TITLE
Seed Phrase Recovery

### ISSUE THREAD

**Issue by VolkerSchiewe** [jolocom/jolocom-lib#300]
**Is your feature request related to a problem? Please describe.**
Key recovery is a problem that every key management system should face. Seed phrase (mnemonic) recovery is a very simple method that many cryptowallets are using.

**Describe the solution you'd like**
The jolocom-lib should provide a method to recover the identity wallet based on the mnemonic phrase. Additionally the mnemonic phrase can be integrated in the creation of of the identity.

**Additional context**
Mnemonics are based on [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)

**Comment by chunningham** [comment]
merged, closing 👍
