### ISSUE TITLE
Decouple the `did:jolo` prefix from internal library functions.

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#328]
### Description

In order to ensure that the library can support interactions with DIDs anchored on different networks (according to different method specifications), we need to ensure the `did:jolo` prefix is never explicitly assumed in the inner / helper functions of the application.

Furthermore we need to ensure the `Registry` and `Resolver` classes are configurable to interface with different networks depending on DID prefixes.

**Comment by mnzaki** [comment]
Closed by #339
