### ISSUE TITLE
Update the `@context` field to include spec mandated entries

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#337]
### Describe
All Did Documents and Verifiable Credentials created by the library should include `@context` entries mandated by the spec, (e.g. "https://www.w3.org/2019/did/v1" for Did Documents). Furthermore, we need to ensure we are using up to date definitions for our terms, and that no errors occur during normalization (e.g. triples being omitted).

### TODO
- [x] Refine / simplify the way we handle context on the lib (currently a map `defaultContext` is used during normalization for all Json LD documents, which can lead to faulty signatures in case  the map is outdated).
- [x] Add stricter unit tests for normalization

**Comment by mnzaki** [comment]
Closed by #338
