### ISSUE TITLE
Social Recovery is not browser compatible

### ISSUE THREAD

**Issue by VolkerSchiewe** [jolocom/jolocom-lib#353]
**Describe the bug**
The package `dark-crystal-secrets` uses `sodium-native` which depends on a node environment. Hence the package is not browser/react-native compatible.

**To Reproduce**
Try to use SocialRecovery in a browser/react-native environment

**Expected behavior**
Should work without node dependencies

**Comment by mnzaki** [comment]
Can't it be shimmed with https://github.com/sodium-friends/sodium-javascript?

**Comment by VolkerSchiewe** [comment]
closed with #354
