### ISSUE TITLE
Fix spelling error in IDigestable

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#366]
### Description
Currently the `IDigestable` interface, and utility validation functions (i.e. `validateDigestable` and `validateDigestables`) are misspelled. This should be addressed.

***Note:** This issue was already addressed as part of PR #340 (comments provide useful context), and eventually merged into 4.0-beta1. In order to simplify the review and feedback process, we decided it can be re-implemented (reusing existing code where possible) as a separate PR.*

*For reference purposes, please see the issues mentioned above, and [this notion document](https://www.notion.so/jolocom/Branch-breakdown-2b81274d6c0d4c9eaa4351415a9a769d)*

**Comment by chunningham** [comment]
addressed
