### ISSUE TITLE
Is this a SDK?

### ISSUE THREAD

**Issue by vongohren** [jolocom/jolocom-lib#375]
### Description
Is this a viable SDK to use for when creating a react native mobile app that utalizes decentralized identity? Incorporating these functions to build around the jolocom network?

Would it be suggested to use this in such a way?

We are working in a country where all have smart phones, and we are trying to deliver a specific identity service, for your skills. We feel that we need to have controll over the services offered on those data points you receive, and not be dependent on what Jolocom implement in their smart wallet app. But we do like the work that has happened and if this can work as an SDK for that, it would be great!

**Comment by mnzaki** [comment]
Yes, this is the official SDK that you can use to implement a react-native mobile app (among other things), just like the jolocom SmartWallet. There are some bits that could be extracted from the wallet to help creating a new mobile app, and that might become its own package later.

> We feel that we need to have controll over the services offered on those data points you receive, and not be dependent on what Jolocom implement in their smart wallet app. 

It would be interesting and useful for us to know what things you would need from the wallet, if you can share that.

**Comment by vongohren** [comment]
@mnzaki that is great to hear! Could we do a short online talk on that? You can contact me on snorre@diwala.io

**Comment by Exulansis** [comment]
@vongohren I've reached out to you directly on Slack, we can schedule a short talk at some point.
Please let me know if you have any further questions, otherwise I will mark this issue as closed.

**Comment by vongohren** [comment]
@Exulansis coolio, thanks. You can resolve this yes.
