### ISSUE TITLE
Outdated jolocom-registry-contract depedency causes installation problems  >node10

### ISSUE THREAD

**Issue by hidde-jan** [jolocom/jolocom-lib#389]
**Describe the bug**

The jolocom-lib depends on a deprecated version of jolocom-registry-contract, which pulls in all kinds of ancient dependency versions. This leads to install problems for node versions later than 10 (scrypt for instance through some web3 and ethereum wallet dependencies).

**To Reproduce**
1. Try to install jolocom-lib on a node version > 10
2. Build fails due to very old child dependencies (node-gyp fails on scrypt)

**Expected behavior**

Being able to cleanly install on newer versions of nodejs

**Desktop (please complete the following information):**
 - Docker image: node:latest (node version v13.6.0)

**Comment by hidde-jan** [comment]
It seems that none of the issues on Github actually get a reply from the developers. The repository for the jolocom-registry-contract package is actually deprecated and replaced by a mono repo, so it seems the dependency is quite an older version. Are there any plans to support newer versions of node with the jolocom-lib package?

**Comment by trappierhall** [comment]
Thanks for the attempt but None of the developers have responded..Sad!

**Comment by mnzaki** [comment]
> It seems that none of the issues on Github actually get a reply from the developers. The repository for the jolocom-registry-contract package is actually deprecated and replaced by a mono repo, so it seems the dependency is quite an older version. Are there any plans to support newer versions of node with the jolocom-lib package?

`jolocom-lib` will support newer versions of node in an upcoming release.
There are (currently) no plans to backport support for later versions of node on the current (4.x) `jolocom-lib`
