### ISSUE TITLE
Ship the library with default configuration.

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#53]
### Description

Currently the library expects a configuration object upon initialization. The object contains data such as the address of a remote IPFS gateway / Ethereum node / the address of the registry smart contract. Not all developers will care about this, therefore the library should ship with the appropriate defaults (Infura for Ethereum, ipfs.jolocom.com for IPFS).

Overwriting these configuration options should be allowed of course.

### TODO
- [x] Include default options.
- [x] Include API for modifying the configuration.

**Comment by katszwn** [comment]
We should consider adding separate initializers for the parts of the library which don't require configuration - like creating and signing claims. For now we just initialize all the elements of the library even if we choose to use the default configuration - which seems like an overkill.

**Comment by Exulansis** [comment]
Technically we ship with default configs now, I will open a new issue for the modular initializers.
